#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{.UserName}}@{{.HostName}} in {{ .PWD }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'os'
    style = 'powerline'
    powerline_symbol = '▓▒░'
    foreground = '#fff'
    background = '#e95420'
    template = ' {{.Icon}} {{if not .WSL }}{{.HostName}} {{end}}'
    background_templates = ['{{ if eq .OS "windows" }}#0078d6{{ end }}', '{{ if eq .OS "linux" }}#1793d1{{ end }}', '{{ if eq .OS "ubuntu" }}#e95420{{ end }}', '{{ if eq .OS "debian" }}#a81d33{{ end }}', '{{ if eq .OS "arch" }}#1793d1{{ end }}']

    [blocks.segments.properties]
      windows = ' '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#cad3f5'
    background = '#494d64'
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      folder_separator_icon = '/'
      style = 'unique'
      max_depth = 3

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#193549'
    background = '#d2ff5e'
    background_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}#ff9248{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#f26d50{{ end }}', '{{ if gt .Ahead 0 }}#89d1dc{{ end }}', '{{ if gt .Behind 0 }}#f17c37{{ end }}']
    template = ' {{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '

    [blocks.segments.properties]
      fetch_stash_count = true
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = "node"
    style = "powerline"
    powerline_symbol = ""
    foreground = "#fff"
    background = "#6ca35e"
    template = "  {{ .Full }} "

  [[blocks.segments]]
    type = 'executiontime'
    style = 'diamond'
    foreground = '#ffffff'
    background = '#5b6078'
    trailing_diamond = ''
    template = '  {{ .FormattedMs }}⠀'

    [blocks.segments.properties]
      always_enabled = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = '#fff'
    template = ' ⚡ '

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'green'
    template = '❯'
    foreground_templates = ['{{ if eq .Code 0 }}green{{ else }}red{{ end }}']
