[".antidote"]
    type = "git-repo"
    url = "https://github.com/mattmc3/antidote.git"

[".config/awesome/awesome-wm-widgets"]
    type = "git-repo"
    url = "https://github.com/streetturtle/awesome-wm-widgets"

[".config/awesome/vicious"]
    type = "git-repo"
    url = "https://github.com/vicious-widgets/vicious.git"

[".config/awesome/nice"]
    type = "git-repo"
    url = "https://github.com/raven2cz/awesome-wm-nice"

['.config/awesome/keyboard_layout']
    type = 'git-repo'
    url = 'https://github.com/echuraev/keyboard_layout'

['.config/awesome/foggy']
    type = 'git-repo'
    url = 'https://gitlab.com/k3rni/foggy.git'
[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
    [".asdf".clone]
        args = ["--branch", "v0.14.0"]
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm.git"
