[".antidote"]
    type = "git-repo"
    url = "https://github.com/mattmc3/antidote.git"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/NvChad/NvChad"
    refreshPeriod = "168h"
    [".config/nvim".clone]
        args = ["--depth 1"]
