$ipc = qs -c noctalia-shell ipc call

# Core binds
bind = SUPER, SPACE, exec, $ipc launcher toggle
bind = SUPER, S, exec, $ipc controlCenter toggle
bind = SUPER, comma, exec, $ipc settings toggle

# Media keys
bindel = , XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = , XF86AudioLowerVolume, exec, $ipc volume decrease
bindl = , XF86AudioMute, exec, $ipc volume muteOutput
bindel = , XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, $ipc brightness decrease

bind = SUPER, Period, exec, $ipc settings toggle

bind = SUPER, x, exec, $ipc sessionMenu toggle
bind = SUPER, Semicolon, exec, $ipc launcher emoji
bind = SUPER, r, exec, $ipc launcher command
bind = SUPER, v, exec, $ipc launcher clipboard

# Plugins
# bind = , Print, exec, $ipc plugin:screen-toolkit annotate

# Sound
bind = , XF86AudioPlay, exec, $ipc media playPause
bind = , XF86AudioNext, exec, $ipc media next
bind = , XF86AudioPrev, exec, $ipc media previous
