#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "$HOME/dotfiles/zsh/zprofile" ]]; then
  source "$HOME/dotfiles/zsh/zprofile"
fi

ZCONFIG="$HOME/dotfiles/zsh"

. "$HOME/.cargo/env"
. "$ZCONFIG/init.zsh"
. "$ZCONFIG/completion.zsh"
. "$ZCONFIG/key-bindings.zsh"
