if [[ -s "/usr/bin/lsd" ]]; then
    alias ls="lsd"
fi

alias vim="nvim"
alias svim="/usr/vim"
alias rsc="ssh -A guillaume.dorce@rsc.bm-services.com 'cd /volumes/databases/; bash -li'"
alias arn="ssh -A guillaume.dorce@arena.bms.lan"
alias ta="tmux a"
alias npm="pnpm"
alias gw="gulp watch"
alias colors="$HOME/.config/scripts/colors.sh"

alias ga="git add"
alias gaa="git add --all"
alias gst="git status"
alias gpr="git pull --rebase"

if [ -z "$SSH_AUTH_SOCK" ] ; then
    eval `ssh-agent -s`
    ssh-add
	clear
fi
